/**
 * Part-of-speech colour palettes.
 *
 * Four palettes — a standard one plus three built natively for the dichromacies — each with a dark
 * and a light variant. Values are `oklch()` because that is what they were authored in; a `rgb()`
 * fallback accompanies each for renderers that cannot parse it. **Never round-trip these through
 * hex**: six of the standard palette's eighteen colours sit outside sRGB deliberately, and hex
 * quantises to 8 bits per channel and clamps them (docs/pos-palette-research.md).
 *
 * The standard palette is hand-authored on two orthogonal semantic axes — four clusters at
 * 45°/135°/225°/315°, each 90° quadrant divided into N equal sub-slots with one member centred in
 * each. The CVD palettes re-project that construction onto the hue axis each vision type retains.
 *
 * Generated by docs/palette-tools; see docs/pos-palettes.md for the rendered comparison.
 */
import type { PartOfSpeech } from "./messages";

/** Which palette to colour with. `theme` defers to the editor's own token colours instead. */
export type PaletteId =
  | "standard"
  | "protanopia"
  | "deuteranopia"
  | "tritanopia";
export type PaletteChoice = PaletteId | "theme";
export type Ground = "dark" | "light";

/** One colour: the authored `oklch()` source, plus an `rgb()` fallback. */
export interface PaletteColor {
  readonly css: string;
  readonly rgb: string;
}

/** Every colour-bearing category, in the palette's own hue order. */
export const PALETTE_CATEGORIES = [
  "utterance",
  "pronoun",
  "noun",
  "adnominal",
  "adjective",
  "adverb",
  "verb",
  "auxiliary",
  "particle"
] as const satisfies ReadonlyArray<Exclude<PartOfSpeech, "other">>;

export type PaletteCategory = (typeof PALETTE_CATEGORIES)[number];

type Palette = Record<PaletteCategory, PaletteColor>;

const color = (css: string, rgb: string): PaletteColor => ({ css, rgb });

/**
 * Standard — hand-authored. Hue is an odd multiple of 22.5° (= 360/16) for six of the nine
 * categories, which is what makes the cross-axis pairs land complementary; the three modifiers
 * compress into the remaining arc because they are the rarest cluster (4.7% of tokens combined).
 * Uniform APCA ~71: lightness varies slightly so that perceived contrast does not.
 */
const STANDARD: Record<Ground, Palette> = {
  dark: {
    utterance: color("oklch(0.84 0.08 157.5)", "rgb(159 219 182)"),
    pronoun: color("oklch(0.84 0.08 202.5)", "rgb(137 218 225)"),
    noun: color("oklch(0.85 0.08 247.5)", "rgb(164 211 255)"),
    adnominal: color("oklch(0.86 0.08 285)", "rgb(203 202 255)"),
    adjective: color("oklch(0.86 0.08 315)", "rgb(229 194 246)"),
    adverb: color("oklch(0.86 0.08 345)", "rgb(248 188 221)"),
    verb: color("oklch(0.86 0.08 22.5)", "rgb(255 189 185)"),
    auxiliary: color("oklch(0.86 0.08 67.5)", "rgb(245 200 153)"),
    particle: color("oklch(0.85 0.08 112.5)", "rgb(206 212 151)")
  },
  light: {
    utterance: color("oklch(0.52 0.12 157.5)", "rgb(10 125 77)"),
    pronoun: color("oklch(0.52 0.12 202.5)", "rgb(0 122 132)"),
    noun: color("oklch(0.54 0.12 247.5)", "rgb(41 115 176)"),
    adnominal: color("oklch(0.55 0.12 285)", "rgb(107 102 180)"),
    adjective: color("oklch(0.55 0.12 315)", "rgb(140 90 161)"),
    adverb: color("oklch(0.55 0.12 345)", "rgb(162 82 130)"),
    verb: color("oklch(0.55 0.12 22.5)", "rgb(173 82 80)"),
    auxiliary: color("oklch(0.54 0.12 67.5)", "rgb(156 95 0)"),
    particle: color("oklch(0.53 0.12 112.5)", "rgb(110 114 0)")
  }
};

/**
 * The CVD palettes. Under dichromacy the hue circle collapses onto a single axis, so clusters
 * separate by hue along that axis and members separate by LIGHTNESS — the channel every vision
 * type retains. Measured surviving axes: protan 90°↔285°, deutan 90°↔270°, tritan 15°↔225°.
 *
 * These are optimised IN the target viewer's perceptual space rather than checked for surviving a
 * simulation, so a deuteranope reading the deuteranopia palette perceives separation comparable to
 * what a normally-sighted reader gets from the standard one.
 */
const PROTANOPIA: Record<Ground, Palette> = {
  dark: {
    utterance: color("oklch(76.7% 0.0850 155.0)", "rgb(135 196 156)"),
    pronoun: color("oklch(89.9% 0.0850 90.0)", "rgb(244 220 157)"),
    noun: color("oklch(79.4% 0.0850 90.0)", "rgb(209 186 123)"),
    adnominal: color("oklch(74.1% 0.0850 220.0)", "rgb(105 184 208)"),
    adjective: color("oklch(84.6% 0.0850 220.0)", "rgb(139 218 243)"),
    adverb: color("oklch(92.6% 0.0506 220.0)", "rgb(194 239 254)"),
    verb: color("oklch(82.0% 0.0850 285.0)", "rgb(190 189 250)"),
    auxiliary: color("oklch(71.4% 0.0850 285.0)", "rgb(157 156 214)"),
    particle: color("oklch(87.3% 0.0850 155.0)", "rgb(168 230 189)")
  },
  light: {
    utterance: color("oklch(58.2% 0.1150 155.0)", "rgb(55 143 92)"),
    pronoun: color("oklch(42.8% 0.0839 90.0)", "rgb(97 76 7)"),
    noun: color("oklch(55.1% 0.1081 90.0)", "rgb(138 110 15)"),
    adnominal: color("oklch(52.0% 0.0909 220.0)", "rgb(16 117 141)"),
    adjective: color("oklch(39.7% 0.0694 220.0)", "rgb(8 79 97)"),
    adverb: color("oklch(64.3% 0.1124 220.0)", "rgb(25 156 188)"),
    verb: color("oklch(61.2% 0.1150 285.0)", "rgb(125 121 198)"),
    auxiliary: color("oklch(45.8% 0.1150 285.0)", "rgb(82 76 148)"),
    particle: color("oklch(48.9% 0.1150 155.0)", "rgb(17 115 66)")
  }
};

const DEUTERANOPIA: Record<Ground, Palette> = {
  dark: {
    utterance: color("oklch(79.4% 0.0850 150.0)", "rgb(148 204 159)"),
    pronoun: color("oklch(87.3% 0.0850 90.0)", "rgb(235 211 148)"),
    noun: color("oklch(76.7% 0.0850 90.0)", "rgb(200 177 115)"),
    adnominal: color("oklch(84.6% 0.0850 210.0)", "rgb(135 220 235)"),
    adjective: color("oklch(92.6% 0.0637 210.0)", "rgb(181 243 254)"),
    adverb: color("oklch(71.4% 0.0850 210.0)", "rgb(92 178 192)"),
    verb: color("oklch(82.0% 0.0850 270.0)", "rgb(175 194 252)"),
    auxiliary: color("oklch(74.1% 0.0850 270.0)", "rgb(150 169 226)"),
    particle: color("oklch(89.9% 0.0850 150.0)", "rgb(182 238 192)")
  },
  light: {
    utterance: color("oklch(45.8% 0.1150 150.0)", "rgb(22 105 51)"),
    pronoun: color("oklch(48.9% 0.0960 90.0)", "rgb(117 93 11)"),
    noun: color("oklch(61.2% 0.1150 90.0)", "rgb(159 128 31)"),
    adnominal: color("oklch(64.3% 0.1068 210.0)", "rgb(25 158 177)"),
    adjective: color("oklch(42.8% 0.0710 210.0)", "rgb(10 89 101)"),
    adverb: color("oklch(55.1% 0.0915 210.0)", "rgb(18 128 143)"),
    verb: color("oklch(39.7% 0.1150 270.0)", "rgb(48 64 132)"),
    auxiliary: color("oklch(52.0% 0.1150 270.0)", "rgb(79 100 171)"),
    particle: color("oklch(58.2% 0.1150 150.0)", "rgb(65 142 85)")
  }
};

const TRITANOPIA: Record<Ground, Palette> = {
  dark: {
    utterance: color("oklch(79.4% 0.0850 85.0)", "rgb(213 184 124)"),
    pronoun: color("oklch(84.6% 0.0814 15.0)", "rgb(253 183 188)"),
    noun: color("oklch(74.1% 0.0850 15.0)", "rgb(219 149 154)"),
    adnominal: color("oklch(71.4% 0.0850 155.0)", "rgb(119 179 140)"),
    adjective: color("oklch(92.6% 0.0850 155.0)", "rgb(185 248 206)"),
    adverb: color("oklch(82.0% 0.0850 155.0)", "rgb(152 213 172)"),
    verb: color("oklch(87.3% 0.0807 225.0)", "rgb(154 225 253)"),
    auxiliary: color("oklch(76.7% 0.0850 225.0)", "rgb(117 191 220)"),
    particle: color("oklch(89.9% 0.0850 85.0)", "rgb(248 218 157)")
  },
  light: {
    utterance: color("oklch(42.8% 0.0841 85.0)", "rgb(100 75 7)"),
    pronoun: color("oklch(58.2% 0.1150 15.0)", "rgb(180 92 101)"),
    noun: color("oklch(45.8% 0.1150 15.0)", "rgb(140 56 67)"),
    adnominal: color("oklch(61.2% 0.1150 155.0)", "rgb(65 152 101)"),
    adjective: color("oklch(48.9% 0.1150 155.0)", "rgb(17 115 66)"),
    adverb: color("oklch(39.7% 0.0942 155.0)", "rgb(8 85 47)"),
    verb: color("oklch(55.1% 0.1002 225.0)", "rgb(18 125 158)"),
    auxiliary: color("oklch(64.3% 0.1150 225.0)", "rgb(31 155 193)"),
    particle: color("oklch(52.0% 0.1023 85.0)", "rgb(132 99 13)")
  }
};

const PALETTES: Record<PaletteId, Record<Ground, Palette>> = {
  standard: STANDARD,
  protanopia: PROTANOPIA,
  deuteranopia: DEUTERANOPIA,
  tritanopia: TRITANOPIA
};

/** Look up one palette. */
export const palette = (id: PaletteId, ground: Ground): Palette =>
  PALETTES[id][ground];

/** The CSS custom-property name a category's colour is published under. */
export const posVar = (category: PaletteCategory): string =>
  `--pos-${category}`;

/**
 * The palette as a CSS custom-property declaration block, `oklch()` with an `rgb()` fallback.
 *
 * The fallback works by declaring each property twice: a renderer that cannot parse `oklch()`
 * discards that declaration and keeps the `rgb()` one, which is the standard CSS fallback pattern
 * and costs nothing at runtime.
 */
export const paletteCss = (id: PaletteId, ground: Ground): string => {
  const p = palette(id, ground);
  const decls = PALETTE_CATEGORIES.flatMap((c) => [
    `${posVar(c)}: ${p[c].rgb};`,
    `${posVar(c)}: ${p[c].css};`
  ]);
  return decls.join("\n  ");
};
